// Code generated by protoc-gen-go. DO NOT EDIT.
// source: objects.proto

package objects

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// TripsPerDay encapsulates the total number of trips in a given day
// Uses date in format 'YYY-MM-DD' as the key
type TripsPerDay struct {
	TripsPerDay          map[string]uint32 `protobuf:"bytes,1,rep,name=trips_per_day,json=tripsPerDay,proto3" json:"trips_per_day,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TripsPerDay) Reset()         { *m = TripsPerDay{} }
func (m *TripsPerDay) String() string { return proto.CompactTextString(m) }
func (*TripsPerDay) ProtoMessage()    {}
func (*TripsPerDay) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{0}
}

func (m *TripsPerDay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TripsPerDay.Unmarshal(m, b)
}
func (m *TripsPerDay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TripsPerDay.Marshal(b, m, deterministic)
}
func (m *TripsPerDay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TripsPerDay.Merge(m, src)
}
func (m *TripsPerDay) XXX_Size() int {
	return xxx_messageInfo_TripsPerDay.Size(m)
}
func (m *TripsPerDay) XXX_DiscardUnknown() {
	xxx_messageInfo_TripsPerDay.DiscardUnknown(m)
}

var xxx_messageInfo_TripsPerDay proto.InternalMessageInfo

func (m *TripsPerDay) GetTripsPerDay() map[string]uint32 {
	if m != nil {
		return m.TripsPerDay
	}
	return nil
}

// CabTripsPerDay is a dictionary of the total number of trips a particular cab has made in a given day
// Uses the medalion(cab id) as the key
type CabTripsPerDay struct {
	CabTrips             map[string]*TripsPerDay `protobuf:"bytes,1,rep,name=cab_trips,json=cabTrips,proto3" json:"cab_trips,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CabTripsPerDay) Reset()         { *m = CabTripsPerDay{} }
func (m *CabTripsPerDay) String() string { return proto.CompactTextString(m) }
func (*CabTripsPerDay) ProtoMessage()    {}
func (*CabTripsPerDay) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{1}
}

func (m *CabTripsPerDay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CabTripsPerDay.Unmarshal(m, b)
}
func (m *CabTripsPerDay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CabTripsPerDay.Marshal(b, m, deterministic)
}
func (m *CabTripsPerDay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CabTripsPerDay.Merge(m, src)
}
func (m *CabTripsPerDay) XXX_Size() int {
	return xxx_messageInfo_CabTripsPerDay.Size(m)
}
func (m *CabTripsPerDay) XXX_DiscardUnknown() {
	xxx_messageInfo_CabTripsPerDay.DiscardUnknown(m)
}

var xxx_messageInfo_CabTripsPerDay proto.InternalMessageInfo

func (m *CabTripsPerDay) GetCabTrips() map[string]*TripsPerDay {
	if m != nil {
		return m.CabTrips
	}
	return nil
}

func init() {
	proto.RegisterType((*TripsPerDay)(nil), "nycab.data.objects.TripsPerDay")
	proto.RegisterMapType((map[string]uint32)(nil), "nycab.data.objects.TripsPerDay.TripsPerDayEntry")
	proto.RegisterType((*CabTripsPerDay)(nil), "nycab.data.objects.CabTripsPerDay")
	proto.RegisterMapType((map[string]*TripsPerDay)(nil), "nycab.data.objects.CabTripsPerDay.CabTripsEntry")
}

func init() { proto.RegisterFile("objects.proto", fileDescriptor_7da965bc36916fc1) }

var fileDescriptor_7da965bc36916fc1 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4f, 0xca, 0x4a,
	0x4d, 0x2e, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xca, 0xab, 0x4c, 0x4e, 0x4c,
	0xd2, 0x4b, 0x49, 0x2c, 0x49, 0xd4, 0x83, 0xca, 0x28, 0x2d, 0x66, 0xe4, 0xe2, 0x0e, 0x29, 0xca,
	0x2c, 0x28, 0x0e, 0x48, 0x2d, 0x72, 0x49, 0xac, 0x14, 0x0a, 0xe1, 0xe2, 0x2d, 0x01, 0x71, 0xe3,
	0x0b, 0x52, 0x8b, 0xe2, 0x53, 0x12, 0x2b, 0x25, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x0c, 0xf4,
	0x30, 0xf5, 0xea, 0x21, 0xe9, 0x43, 0x66, 0xbb, 0xe6, 0x95, 0x14, 0x55, 0x06, 0x71, 0x97, 0x20,
	0x44, 0xa4, 0xec, 0xb8, 0x04, 0xd0, 0x15, 0x08, 0x09, 0x70, 0x31, 0x67, 0xa7, 0x82, 0xcc, 0x67,
	0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x85, 0x44, 0xb8, 0x58, 0xcb, 0x12, 0x73, 0x4a, 0x53, 0x25, 0x98,
	0x14, 0x18, 0x35, 0x78, 0x83, 0x20, 0x1c, 0x2b, 0x26, 0x0b, 0x46, 0xa5, 0xbd, 0x8c, 0x5c, 0x7c,
	0xce, 0x89, 0x49, 0xc8, 0x0e, 0xf5, 0xe5, 0xe2, 0x4c, 0x4e, 0x4c, 0x8a, 0x07, 0xdb, 0x82, 0xcf,
	0x91, 0xa8, 0xda, 0xe0, 0x5c, 0x88, 0x23, 0x39, 0x92, 0xa1, 0x5c, 0xa9, 0x18, 0x2e, 0x5e, 0x14,
	0x29, 0x2c, 0xce, 0x33, 0x45, 0x76, 0x1e, 0xb7, 0x91, 0x3c, 0x81, 0x20, 0x41, 0x72, 0xbf, 0x93,
	0x6a, 0x94, 0x72, 0x6e, 0x5e, 0x7e, 0x59, 0x66, 0x72, 0x66, 0xbe, 0x5e, 0x72, 0x7e, 0xae, 0x3e,
	0x58, 0xa7, 0x3e, 0x38, 0x56, 0x92, 0xf3, 0x73, 0xf4, 0xa1, 0xba, 0x93, 0xd8, 0xc0, 0x22, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xee, 0x31, 0x1f, 0x7c, 0xb8, 0x01, 0x00, 0x00,
}
