version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: mysql_server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: mysql_adminer
    restart: always
    ports:
      - 8080:8080
